name: dotnet package

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: [self-hosted, linux]
    env:
      BUILD: 'emt-sdk/bin/Release/netstandard2.0'
      # This pollutes working directory if we ever want to use git in the workflow!
      DOTNET_INSTALL_DIR: './.dotnet'
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          submodules: recursive
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore emt-sdk
      - name: Build
        run: dotnet build emt-sdk --configuration Release --no-restore
      - name: Package
        run: |
          cd ${BUILD}/UnityPackage/
          tar zcf emt-sdk.tgz package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: emt-sdk
          path: emt-sdk/bin/Release/netstandard2.0/UnityPackage/emt-sdk.tgz
